apiVersion: v1
kind: Service
metadata:
  name: slackbot-loadbalancer
spec:
  selector:
    app: slackbot
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  clusterIP: 10.100.125.131
  loadBalancerIP: 78.11.24.19
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155
