# This will deploy an nginx web server
# apiVersion: v1
# kind: Pod
# metadata:
#   name: slackbot
#   labels:
#     app: 
# spec:
#   containers:
#     - name: web-server
#       image: nginx:latest
#       ports:
#         - containerPort: 4000
#           protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: slackbot
  labels:
    app: slackbot
spec:
  containers:
    - name: web-server
      image: slackbot
      ports:
        - containerPort: 4000
          protocol: TCP