# This is the service that will allow the nginx container to access the internal IP and then the interwebs.
apiVersion: v1
kind: Service
metadata:
  name: slackbot
  labels:
   app: slackbot
spec:
  selector:
    app: slackbot
  ports:
    - port: 4000
      protocol: TCP
  type: NodePort