# This is the service for the data tier used with redis
apiVersion: v1
kind: Service
metadata:
  name: example01-data-tier
spec:
  selector:
    app: example01
    tier: data
  ports:
    - name: redis
      port: 6379
      protocol: TCP